name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1
      EB_APP_NAME: airspace-viewer
      EB_ENV_NAME: airspace-viewer-prod
      EB_S3_BUCKET: airspace-viewer-deployments-eu-west-1-47511461cf8

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test application
      run: |
        python test_app.py

    - name: Generate deployment package
      run: |
        zip -r deploy.zip . -x \
                ".github/*" \
                ".secrets/*" \
                ".venv/*" \
                "*__pycache__/*" \
                "*.egg-info*" \
                "*.git*" \
                "*.md" \
                "*.pyc" \
                "*.pyo" \
                "*.sh" \
                "test_app.py"
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.EB_APP_NAME }}
        environment_name: ${{ env.EB_ENV_NAME }}
        version_label: deploy-${{ github.run_number }}-${{ github.sha }}
        region: ${{ env.AWS_REGION }}
        deployment_package: deploy.zip
        existing_bucket_name: ${{ env.EB_S3_BUCKET }}
        version_description: "Deployment from commit ${{ github.sha }}"
        wait_for_deployment: true
        wait_for_environment_recovery: 120
    - name: Configure environment variables in Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_REGION
        
        # Set environment variables in Elastic Beanstalk
        aws elasticbeanstalk update-environment \
          --application-name $EB_APP_NAME \
          --environment-name $EB_ENV_NAME \
          --option-settings \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=FLASK_SECRET_KEY,Value="$FLASK_SECRET_KEY" \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=FLASK_ENV,Value=production
