name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1
      EB_APP_NAME: airspace-viewer
      EB_ENV_NAME: airspace-viewer-prod
      EB_S3_BUCKET: airspace-viewer-deployments-eu-west-1-47511461cf8

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip source bundle
      run: |
        zip -r app.zip . -x "*.git*" "__pycache__/*" "*.sh" "*.pyc" "*.pyo" "*.egg-info*" ".github/*"

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_REGION

        # Check if deploy user has access to the environment
        echo "Checking access to Elastic Beanstalk environment..."
        aws elasticbeanstalk describe-environments \
          --application-name $EB_APP_NAME \
          --environment-names $EB_ENV_NAME \
          --query 'Environments[0].{Name:EnvironmentName,Status:Status,Health:Health}' \
          --output table

        # Verify environment exists and is accessible
        ENV_STATUS=$(aws elasticbeanstalk describe-environments \
          --application-name $EB_APP_NAME \
          --environment-names $EB_ENV_NAME \
          --query 'Environments[0].Status' \
          --output text 2>/dev/null || echo "NOT_FOUND")

        if [ "$ENV_STATUS" = "NOT_FOUND" ] || [ "$ENV_STATUS" = "None" ]; then
          echo "Error: Cannot access environment $EB_ENV_NAME in application $EB_APP_NAME"
          echo "Please check:"
          echo "1. Environment name and application name are correct"
          echo "2. Deploy user has elasticbeanstalk:DescribeEnvironments permission"
          echo "3. Deploy user has access to the specific environment"
          exit 1
        fi

        if [ "$ENV_STATUS" = "Terminated" ]; then
          echo "Error: Environment $EB_ENV_NAME is in Terminated status"
          echo "Please recreate the environment before deploying"
          exit 1
        fi

        echo "Environment access confirmed. Status: $ENV_STATUS"

        # Set environment variables in Elastic Beanstalk
        aws elasticbeanstalk update-environment \
          --application-name $EB_APP_NAME \
          --environment-name $EB_ENV_NAME \
          --option-settings \
            Namespace=aws:elasticbeanstalk:application:environment,OptionName=FLASK_SECRET_KEY,Value="$FLASK_SECRET_KEY"

        VERSION_LABEL="deploy-$(date +%Y%m%d%H%M%S)"
        aws s3 cp app.zip s3://$EB_S3_BUCKET/$VERSION_LABEL.zip
        aws elasticbeanstalk create-application-version \
          --application-name $EB_APP_NAME \
          --version-label $VERSION_LABEL \
          --source-bundle S3Bucket=$EB_S3_BUCKET,S3Key=$VERSION_LABEL.zip

        aws elasticbeanstalk update-environment \
          --application-name $EB_APP_NAME \
          --environment-name $EB_ENV_NAME \
          --version-label $VERSION_LABEL
